import { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import Link from "next/link";
import { Alert, Button } from "@mui/material";
import { useForm } from "react-hook-form";
import { useGoogleLogin } from "@react-oauth/google";
import axios from "axios";

import styles from "./Signup.module.scss";

import { fetchSignup } from "../../store/slices/authSlice";
import Head from "next/head";
import { useRouter } from "next/router";

const Signup = () => {
  //const navigate = useNavigate();
  const dispatch = useDispatch();
  const router = useRouter();

  const { userInfo, error } = useSelector((state) => state.auth);

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm({
    defaultValues: {
      username: "",
      password: "",
      passwordRepeat: "",
      email: "",
      full_name: "",
    },
    mode: "onSubmit",
  });

  const googleRegister = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      try {
        await onSubmit({
          provider: "Google",
          token: tokenResponse.access_token,
        });
      } catch (err) {
        console.log(err);
      }
    },
  });

  const onSubmit = (values) => {
    console.log(values);
    dispatch(fetchSignup(values));
  };

  useEffect(() => {
    if (userInfo) {
      router.push("/login");
    }
  }, [userInfo]);

  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.background}>
          <div className={styles.contentContainer}>
            <Link href="/" className={styles.logo}>
              <h2>drawly</h2>
            </Link>
            <div className={styles.heading}>
              <h1>Welcome</h1>
              <span>Create your new account</span>
            </div>

            <Button
              onClick={() => googleRegister()}
              className={styles.oauthBtn}
            >
              <img src="/assets/google_icon.png" alt="" />
              <span>Sign up with Google</span>
            </Button>

            <div className={styles.hrText}>
              <div></div>
              <span>or</span>
              <div></div>
            </div>

            {error && (
              <Alert severity="error" style={{ borderRadius: "10px" }}>
                {error}
              </Alert>
            )}

            <form onSubmit={handleSubmit(onSubmit)}>
              <div className={styles.inputs}>
                {!Object.keys(errors).length == 0 && (
                  <Alert severity="warning" style={{ borderRadius: "10px" }}>
                    {Object.values(errors)[0].message}
                  </Alert>
                )}
                <div className={styles.form}>
                  <label htmlFor="username">Username</label>
                  <div className={styles.field}>
                    <input
                      type="text"
                      id="username"
                      required
                      minLength={3}
                      {...register("username")}
                      placeholder="Create username"
                    />
                  </div>
                </div>
                <div className={styles.form}>
                  <label htmlFor="name">Full Name</label>
                  <div className={styles.field}>
                    <input
                      type="text"
                      id="name"
                      required
                      {...register("full_name", {
                        pattern: {
                          value: /^([\w]{2,})+\s+([\w\s]{2,})+$/i,
                          message: "Please, enter your real name",
                        },
                      })}
                      placeholder="Your name"
                    />
                  </div>
                </div>
                <div className={styles.form}>
                  <label htmlFor="email">Email</label>
                  <div className={styles.field}>
                    <input
                      type="email"
                      id="email"
                      required
                      {...register("email", {
                        pattern: {
                          value:
                            /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i,
                          message: "Please, enter a valid email",
                        },
                      })}
                      placeholder="user@example.com"
                    />
                  </div>
                </div>
                <div className={styles.form}>
                  <label htmlFor="password">Password</label>
                  <div className={styles.field}>
                    <input
                      type="password"
                      id="password"
                      required
                      {...register("password", {
                        pattern: {
                          value: /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/,
                          message: "Password is not strong enough",
                        },
                      })}
                      placeholder="Create password"
                    />
                  </div>
                </div>
                <div className={styles.form}>
                  <label htmlFor="confirm">Repeat Password</label>
                  <div className={styles.field}>
                    <input
                      type="password"
                      id="confirm"
                      required
                      {...register("passwordRepeat", {
                        validate: (value) => {
                          if (watch("password") !== value) {
                            return "Your passwords do no match";
                          }
                        },
                      })}
                      placeholder="Repeat password"
                    />
                  </div>
                </div>
              </div>
              <div className={styles.button}>
                <Button type="submit" variant="contained">
                  Sign up
                </Button>
                <span>Already have an account?</span>
                <Link href="/login">Log in</Link>
              </div>
            </form>
          </div>
          <div className={styles.image}>
            <div className={styles.text}>
              <h2>drawly</h2>
            </div>
            <img src="/assets/bg/signup.jpg" alt="" />
          </div>
        </section>
      </main>
    </>
  );
};

export default Signup;
