import Head from 'next/head'
import { ToolBar } from "@/components/ToolBar/ToolBar";
import { Canvas } from "@/components/Canvas/Canvas";
import {useState} from "react";
import {Tool} from "@/data/Tools";

export default function Home() {
  const [tool, setTool] = useState<number>(0)

  return (
    <>
      <Head>
        <title>drawly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ width: '100wh', height: '100vh' }}>
          <ToolBar tool={tool} setTool={setTool}/>
          <Canvas tool={tool} width='1000px' height='700px' />
      </main>
    </>
  )
}
