import Head from 'next/head'
import { ToolBar } from "@/components/ToolBar/ToolBar";
import {MainCanvas} from "@/components/MainCanvas/MainCanvas";

export default function Home() {
  return (
    <>
      <Head>
        <title>drawly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <ToolBar />
          <MainCanvas />
      </main>
    </>
  )
}
