import Head from 'next/head'
import { ToolBar } from "@/components/ToolBar/ToolBar";
import { Canvas } from "@/components/Canvas/Canvas";
import { MainCanvas } from "@/components/MainCanvas/MainCanvas";
import {useState, useRef, useEffect} from "react";

export default function Home() {
    const styles = {
        //transform: `translate(${position.x}px, ${position.y}px)`,
        width: '100wh',
        height: '100vh'
    };

  return (
    <>
      <Head>
        <title>drawly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <>
            <ToolBar />
            <main style={styles}>
                <Canvas width='1000px' height='700px' />
                {/*<MainCanvas />*/}
            </main>
        </>
    </>
  )
}
