import { useState, useEffect } from "react";
// import { Link, useNavigate } from 'react-router-dom';
import Link from "next/link";
import { useGoogleLogin } from "@react-oauth/google";
import { useDispatch, useSelector } from "react-redux";
import { useForm } from "react-hook-form";
import { Alert, Button } from "@mui/material";
import axios from "axios";

import styles from "./Login.module.scss";

import { fetchLogin } from "@/store/slices/authSlice";
import Head from "next/head";
import { useRouter } from "next/router";

const Login = () => {
  const router = useRouter();
  const dispatch = useDispatch();

  let { userInfo, error } = useSelector((state) => state.auth);

  const { register, handleSubmit } = useForm({
    defaultValues: {
      email: "",
      password: "",
    },
    mode: "onChange",
  });

  const login = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      try {
        await onSubmit({
          provider: "Google",
          token: tokenResponse.access_token,
        });
      } catch (err) {
        console.log(err);
      }
    },
  });

  const onSubmit = async (values) => {
    console.log(values);
    dispatch(fetchLogin(values));
  };

  useEffect(() => {
    if (userInfo) {
      localStorage.setItem("userInfo", JSON.stringify(userInfo));
      router.push("/home");
    }
  }, [userInfo]);

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.background}>
          <div className={styles.contentContainer}>
            <Link href="/" className={styles.logo}>
              <h2>drawly</h2>
            </Link>
            <div className={styles.heading}>
              <h1>Sign in</h1>
              <span>
                Welcome back! Please enter your
                <br />
                credentials
              </span>
            </div>

            <Button onClick={() => login()} className={styles.oauthBtn}>
              <img src="/assets/google_icon.png" alt="" />
              <span>Sign in with Google</span>
            </Button>

            <div className={styles.hrText}>
              <div></div>
              <span>or</span>
              <div></div>
            </div>

            {error && (
              <Alert severity="error" style={{ borderRadius: "10px" }}>
                {error}
              </Alert>
            )}

            <form onSubmit={handleSubmit(onSubmit)}>
              <div className={styles.inputs}>
                <div className={styles.form}>
                  <label>Email</label>
                  <div className={styles.field}>
                    <input
                      type="email"
                      id="email"
                      {...register("email", {
                        pattern: {
                          value:
                            /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i,
                          message: "Please, enter a valid email",
                        },
                      })}
                      placeholder="user@example.com"
                    />
                  </div>
                </div>
                <div className={styles.form}>
                  <label>Password</label>
                  <div className={styles.field}>
                    <input
                      type="password"
                      {...register("password", { required: "Input password" })}
                      placeholder="Your password"
                    />
                  </div>
                  <Link href="/reset-password">Forgot password?</Link>
                </div>
              </div>
              <div className={styles.button}>
                <Button variant="contained" type="submit">
                  Log in
                </Button>
                <span>Don’t have an account?</span>
                <Link href="/signup">Sign up</Link>
              </div>
            </form>
          </div>
          <div className={styles.image}>
            <div className={styles.text}>
              <h2>drawly</h2>
            </div>
            <img src="/assets/bg/login.jpg" alt="" />
          </div>
        </section>
      </main>
    </>
  );
};

export default Login;
