import Head from "next/head";
import Link from 'next/link';
import {Container, Button} from '@mui/material';

import styles from './Home.module.scss';
import {CanvasCard} from "@/components/CanvasCard/CanvasCard";

const Home = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container maxWidth='xl' className={styles.container}>
                    <nav className={styles.navigationContainer}>
                        <Link href='/' className={styles.logoLink}>
                            <h1 className={styles.logoText}>drawly</h1>
                        </Link>
                        <div className={styles.menu}>
                            <Button>Settings</Button>
                            <Button>Logout</Button>
                        </div>
                    </nav>
                    <div className={styles.canvasContainer}>
                        <div className={styles.heading}>
                            <h1>Canvases</h1>
                            <Button variant='contained' className={styles.button}>New</Button>
                        </div>
                        <div className={styles.cardContainer}>
                            <CanvasCard />
                            <CanvasCard />
                            <CanvasCard />
                            <CanvasCard />
                            <CanvasCard />
                        </div>
                    </div>
                </Container>
            </main>
        </>
    )
}

export default Home;