version: '3.0'
services:
  db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: "uevent"
      POSTGRES_USER: "uevent"
      POSTGRES_PASSWORD: "uevent"
    ports:
      - '5932:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: