import { useEffect } from "react";
import Link from "next/link";
import { useSelector, useDispatch } from "react-redux";
import { useRouter } from "next/router";

import styles from "./ConfirmEmail.module.scss";
import { fetchConfirmEmail } from "@/store/slices/authSlice";
import Head from "next/head";

const ConfirmEmail = () => {
  const dispatch = useDispatch();

  const { userInfo, error } = useSelector((state) => state.auth);
  const { query } = useRouter();

  useEffect(() => {
    const token = query.token;
    dispatch(fetchConfirmEmail(token));
  }, []);

  return (
    <>
      <Head>
        <title>Confirm Email</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.background}>
          <div className={styles.contentContainer}>
            <Link href="/" className={styles.logo}>
              <h2>drawly</h2>
            </Link>
            <div className={styles.content}>
              {error && (
                <>
                  <h1>{error}</h1>
                </>
              )}
              {userInfo && (
                <>
                  <h1>Email successfully confirmed</h1>
                </>
              )}
            </div>
          </div>
          <div className={styles.image}>
            <div className={styles.text}>
              <h2>Drawly</h2>
            </div>
            <img src="/assets/bg/confirm.jpg" alt="" />
          </div>
        </section>
      </main>
    </>
  );
};

export default ConfirmEmail;
